version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-school
    working_dir: /var/www/html
    volumes:
      - ./escoles:/var/www/html  # Sincroniza con la carpeta local
    ports:
      - "9000:9000"
    environment:
      - COMPOSER_MEMORY_LIMIT=-1

  web:
    image: nginx:alpine
    container_name: laravel-nginx1
    ports:
      - "8088:80"
    volumes:
      - ./escoles:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-DB
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./escoles/mysql:/var/lib/mysql
      
volumes:
  dbdata:
    driver: local

networks:
  default:
    name: school-network
